"""Add indexes to foreign key columns

Revision ID: 8e5b07fb1868
Revises: b55cf0427df3
Create Date: 2025-10-10 12:48:13.612075

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e5b07fb1868"
down_revision: str | None = "b55cf0427df3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_hame_document_plan_id"),
        "document",
        ["plan_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_land_use_area_id"),
        "lifecycle_date",
        ["land_use_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_line_id"),
        "lifecycle_date",
        ["line_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_other_area_id"),
        "lifecycle_date",
        ["other_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_plan_id"),
        "lifecycle_date",
        ["plan_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_plan_proposition_id"),
        "lifecycle_date",
        ["plan_proposition_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_plan_regulation_id"),
        "lifecycle_date",
        ["plan_regulation_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_point_id"),
        "lifecycle_date",
        ["point_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_proposition_plan_regulation_group_id"),
        "plan_proposition",
        ["plan_regulation_group_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_regulation_plan_regulation_group_id"),
        "plan_regulation",
        ["plan_regulation_group_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_source_data_plan_id"),
        "source_data",
        ["plan_id"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hame_source_data_plan_id"), table_name="source_data", schema="hame"
    )
    op.drop_index(
        op.f("ix_hame_plan_regulation_plan_regulation_group_id"),
        table_name="plan_regulation",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_proposition_plan_regulation_group_id"),
        table_name="plan_proposition",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_point_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_plan_regulation_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_plan_proposition_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_plan_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_other_area_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_line_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_land_use_area_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_document_plan_id"), table_name="document", schema="hame"
    )
    # ### end Alembic commands ###
