"""fix_trgfunc_prevent_land_use_area_overlaps

Revision ID: a2baec3a78b6
Revises: 93209861322d
Create Date: 2025-08-13 07:32:33.914161

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "a2baec3a78b6"
down_revision: Union[str, None] = "93209861322d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_land_use_area_prevent_overlap = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_prevent_overlap()",
        definition="RETURNS TRIGGER AS $$\n    DECLARE\n        overlapping_id UUID;\n    BEGIN\n        SELECT id INTO overlapping_id\n        FROM hame.land_use_area\n        WHERE\n            plan_id = NEW.plan_id\n            AND id IS DISTINCT FROM NEW.id\n            AND ST_Overlaps(geom, NEW.geom)\n        ;\n        IF overlapping_id IS NOT NULL THEN\n            RAISE EXCEPTION 'Geometries overlap\\: % - %',\n                NEW.id, overlapping_id\n                USING HINT = 'Two land use areas cannot overlap';\n        END IF;\n        RETURN NEW;\n    END;\n    $$ language 'plpgsql'",
    )
    op.replace_entity(hame_trgfunc_land_use_area_prevent_overlap)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_land_use_area_prevent_overlap = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_prevent_overlap()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        overlapping_id UUID;\n    BEGIN\n        SELECT id INTO overlapping_id\n        FROM hame.land_use_area\n        WHERE\n            plan_id = NEW.plan_id\n            AND ST_Overlaps(geom, NEW.geom)\n        ;\n        IF overlapping_id IS NOT NULL THEN\n            RAISE EXCEPTION 'Geometries overlap\\: % - %',\n                NEW.id, overlapping_id\n                USING HINT = 'Two land use areas cannot overlap';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.replace_entity(hame_trgfunc_land_use_area_prevent_overlap)
    # ### end Alembic commands ###
