"""Add indexe to regulation group type

Revision ID: d0fb86348f85
Revises: 8e5b07fb1868
Create Date: 2025-10-10 13:07:50.602334

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0fb86348f85"
down_revision: str | None = "8e5b07fb1868"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_type_of_plan_regulation_group_value",
        "type_of_plan_regulation_group",
        ["value"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_hame_plan_regulation_group_type_of_plan_regulation_group_id"),
        "plan_regulation_group",
        ["type_of_plan_regulation_group_id"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hame_plan_regulation_group_type_of_plan_regulation_group_id"),
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.drop_index(
        "ix_type_of_plan_regulation_group_value",
        table_name="type_of_plan_regulation_group",
        schema="codes",
    )
    # ### end Alembic commands ###
