"""Remove unused indexes

Revision ID: 838e36749db6
Revises: d0fb86348f85
Create Date: 2025-10-10 13:36:27.505852

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "838e36749db6"
down_revision: str | None = "d0fb86348f85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hame_additional_information_type_additional_information_id"),
        table_name="additional_information",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_land_use_area_type_of_underground_id"),
        table_name="land_use_area",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_line_type_of_underground_id"), table_name="line", schema="hame"
    )
    op.drop_index(
        op.f("ix_hame_other_area_type_of_underground_id"),
        table_name="other_area",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_regulation_group_type_of_plan_regulation_group_id"),
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_point_type_of_underground_id"), table_name="point", schema="hame"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_hame_point_type_of_underground_id"),
        "point",
        ["type_of_underground_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_regulation_group_type_of_plan_regulation_group_id"),
        "plan_regulation_group",
        ["type_of_plan_regulation_group_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_other_area_type_of_underground_id"),
        "other_area",
        ["type_of_underground_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_line_type_of_underground_id"),
        "line",
        ["type_of_underground_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_land_use_area_type_of_underground_id"),
        "land_use_area",
        ["type_of_underground_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_additional_information_type_additional_information_id"),
        "additional_information",
        ["type_additional_information_id"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###
