"""remove_regulation_group_short_name_uniqueness

Revision ID: 043da5985f91
Revises: 3dcbee6ccdc2
Create Date: 2025-09-08 14:43:58.306524

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "043da5985f91"
down_revision: Union[str, None] = "3dcbee6ccdc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_plan_regulation_group_plan_id_short_name"),
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.create_index(
        "ix_plan_regulation_group_plan_id_short_name",
        "plan_regulation_group",
        ["plan_id", "short_name"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_plan_regulation_group_plan_id_short_name",
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.create_index(
        op.f("ix_plan_regulation_group_plan_id_short_name"),
        "plan_regulation_group",
        ["plan_id", "short_name"],
        unique=True,
        schema="hame",
    )
    # ### end Alembic commands ###
