"""remove old to_be_exported field

Revision ID: 2010b7bcc3b4
Revises: 82a732dbaebe
Create Date: 2025-03-17 16:16:40.527826

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2010b7bcc3b4"
down_revision: Union[str, None] = "3ff7fafa3cca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "to_be_exported", schema="hame")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan",
        sa.Column(
            "to_be_exported",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        schema="hame",
    )
    # ### end Alembic commands ###
