"""remove_trigger_preventing_overlapping_land_use_areas

Revision ID: ea2990f1379b
Revises: 1a08c5c2ca24
Create Date: 2025-08-25 12:06:29.888300

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "ea2990f1379b"
down_revision: Union[str, None] = "1a08c5c2ca24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_land_use_area_trg_land_use_area_prevent_overlap = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_prevent_overlap",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.land_use_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_land_use_area_prevent_overlap()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_prevent_overlap)

    hame_trgfunc_land_use_area_prevent_overlap = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_prevent_overlap()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        overlapping_id UUID;\n    BEGIN\n        SELECT id INTO overlapping_id\n        FROM hame.land_use_area\n        WHERE\n            plan_id = NEW.plan_id\n            AND id IS DISTINCT FROM NEW.id\n            AND ST_Overlaps(geom, NEW.geom)\n        ;\n        IF overlapping_id IS NOT NULL THEN\n            RAISE EXCEPTION 'Geometries overlap\\: % - %',\n                NEW.id, overlapping_id\n                USING HINT = 'Two land use areas cannot overlap';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_land_use_area_prevent_overlap)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_land_use_area_prevent_overlap = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_prevent_overlap()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        overlapping_id UUID;\n    BEGIN\n        SELECT id INTO overlapping_id\n        FROM hame.land_use_area\n        WHERE\n            plan_id = NEW.plan_id\n            AND id IS DISTINCT FROM NEW.id\n            AND ST_Overlaps(geom, NEW.geom)\n        ;\n        IF overlapping_id IS NOT NULL THEN\n            RAISE EXCEPTION 'Geometries overlap\\: % - %',\n                NEW.id, overlapping_id\n                USING HINT = 'Two land use areas cannot overlap';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_land_use_area_prevent_overlap)

    hame_land_use_area_trg_land_use_area_prevent_overlap = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_prevent_overlap",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.land_use_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_land_use_area_prevent_overlap()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_prevent_overlap)

    # ### end Alembic commands ###
