"""Make name mandatory

Revision ID: 3dcbee6ccdc2
Revises: ea2990f1379b
Create Date: 2025-09-09 17:16:24.097177

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3dcbee6ccdc2"
down_revision: Union[str, None] = "ea2990f1379b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('UPDATE hame.plan SET name = \'{"fin": "Nimetön"}\' WHERE name IS NULL')
    op.alter_column(
        "plan",
        "name",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan",
        "name",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        schema="hame",
    )
    # ### end Alembic commands ###
