"""Add created at triggers

Revision ID: c78e25767496
Revises: 7831e76a7758
Create Date: 2025-10-03 12:52:57.484325

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "c78e25767496"
down_revision: str | None = "7831e76a7758"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_created_at = PGFunction(
        schema="hame",
        signature="trgfunc_created_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.created_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_created_at)

    hame_trgfunc_no_created_at_update = PGFunction(
        schema="hame",
        signature="trgfunc_no_created_at_update()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.created_at = OLD.created_at;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_no_created_at_update)

    hame_document_trg_document_created_at = PGTrigger(
        schema="hame",
        signature="trg_document_created_at",
        on_entity="hame.document",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_document_trg_document_created_at)

    codes_type_of_decision_maker_trg_type_of_decision_maker_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_decision_maker_created_at",
        on_entity="codes.type_of_decision_maker",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_decision_maker\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_type_of_decision_maker_trg_type_of_decision_maker_created_at)

    hame_lifecycle_date_trg_lifecycle_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_created_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.lifecycle_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_created_at)

    codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_created_at = PGTrigger(
        schema="codes",
        signature="trg_legal_effects_of_master_plan_created_at",
        on_entity="codes.legal_effects_of_master_plan",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.legal_effects_of_master_plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_created_at
    )

    hame_organisation_trg_organisation_created_at = PGTrigger(
        schema="hame",
        signature="trg_organisation_created_at",
        on_entity="hame.organisation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.organisation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_organisation_trg_organisation_created_at)

    codes_municipality_trg_municipality_created_at = PGTrigger(
        schema="codes",
        signature="trg_municipality_created_at",
        on_entity="codes.municipality",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.municipality\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_municipality_trg_municipality_created_at)

    codes_type_of_source_data_trg_type_of_source_data_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_source_data_created_at",
        on_entity="codes.type_of_source_data",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_type_of_source_data_trg_type_of_source_data_created_at)

    codes_language_trg_language_created_at = PGTrigger(
        schema="codes",
        signature="trg_language_created_at",
        on_entity="codes.language",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.language\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_language_trg_language_created_at)

    codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_created_at = PGTrigger(
        schema="codes",
        signature="trg_name_of_plan_case_decision_created_at",
        on_entity="codes.name_of_plan_case_decision",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.name_of_plan_case_decision\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_created_at
    )

    codes_lifecycle_status_trg_lifecycle_status_created_at = PGTrigger(
        schema="codes",
        signature="trg_lifecycle_status_created_at",
        on_entity="codes.lifecycle_status",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.lifecycle_status\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_lifecycle_status_trg_lifecycle_status_created_at)

    hame_event_date_trg_event_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_created_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.event_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_event_date_trg_event_date_created_at)

    codes_category_of_publicity_trg_category_of_publicity_created_at = PGTrigger(
        schema="codes",
        signature="trg_category_of_publicity_created_at",
        on_entity="codes.category_of_publicity",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.category_of_publicity\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_category_of_publicity_trg_category_of_publicity_created_at)

    codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_verbal_plan_regulation_created_at",
        on_entity="codes.type_of_verbal_plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_verbal_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_created_at
    )

    codes_retention_time_trg_retention_time_created_at = PGTrigger(
        schema="codes",
        signature="trg_retention_time_created_at",
        on_entity="codes.retention_time",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.retention_time\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_retention_time_trg_retention_time_created_at)

    hame_plan_regulation_trg_plan_regulation_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_created_at",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_plan_regulation_trg_plan_regulation_created_at)

    hame_point_trg_point_created_at = PGTrigger(
        schema="hame",
        signature="trg_point_created_at",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_point_trg_point_created_at)

    codes_type_of_additional_information_trg_type_of_additional_information_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_additional_information_created_at",
        on_entity="codes.type_of_additional_information",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_type_of_additional_information_trg_type_of_additional_information_created_at
    )

    codes_plan_type_trg_plan_type_created_at = PGTrigger(
        schema="codes",
        signature="trg_plan_type_created_at",
        on_entity="codes.plan_type",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.plan_type\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_plan_type_trg_plan_type_created_at)

    codes_type_of_processing_event_trg_type_of_processing_event_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_processing_event_created_at",
        on_entity="codes.type_of_processing_event",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_processing_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_type_of_processing_event_trg_type_of_processing_event_created_at
    )

    hame_land_use_area_trg_land_use_area_created_at = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_created_at",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_created_at)

    hame_plan_trg_plan_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_created_at",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_plan_trg_plan_created_at)

    hame_source_data_trg_source_data_created_at = PGTrigger(
        schema="hame",
        signature="trg_source_data_created_at",
        on_entity="hame.source_data",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_source_data_trg_source_data_created_at)

    codes_plan_theme_trg_plan_theme_created_at = PGTrigger(
        schema="codes",
        signature="trg_plan_theme_created_at",
        on_entity="codes.plan_theme",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.plan_theme\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_plan_theme_trg_plan_theme_created_at)

    codes_type_of_document_trg_type_of_document_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_document_created_at",
        on_entity="codes.type_of_document",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_type_of_document_trg_type_of_document_created_at)

    hame_additional_information_trg_additional_information_created_at = PGTrigger(
        schema="hame",
        signature="trg_additional_information_created_at",
        on_entity="hame.additional_information",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_additional_information_trg_additional_information_created_at)

    codes_personal_data_content_trg_personal_data_content_created_at = PGTrigger(
        schema="codes",
        signature="trg_personal_data_content_created_at",
        on_entity="codes.personal_data_content",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.personal_data_content\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_personal_data_content_trg_personal_data_content_created_at)

    hame_plan_proposition_trg_plan_proposition_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_created_at",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_proposition\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_plan_proposition_trg_plan_proposition_created_at)

    hame_line_trg_line_created_at = PGTrigger(
        schema="hame",
        signature="trg_line_created_at",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_line_trg_line_created_at)

    codes_type_of_interaction_event_trg_type_of_interaction_event_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_interaction_event_created_at",
        on_entity="codes.type_of_interaction_event",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_interaction_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_type_of_interaction_event_trg_type_of_interaction_event_created_at
    )

    codes_administrative_region_trg_administrative_region_created_at = PGTrigger(
        schema="codes",
        signature="trg_administrative_region_created_at",
        on_entity="codes.administrative_region",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.administrative_region\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_administrative_region_trg_administrative_region_created_at)

    hame_other_area_trg_other_area_created_at = PGTrigger(
        schema="hame",
        signature="trg_other_area_created_at",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_other_area_trg_other_area_created_at)

    codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_group_created_at",
        on_entity="codes.type_of_plan_regulation_group",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_created_at
    )

    codes_type_of_plan_regulation_trg_type_of_plan_regulation_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_created_at",
        on_entity="codes.type_of_plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        codes_type_of_plan_regulation_trg_type_of_plan_regulation_created_at
    )

    codes_type_of_underground_trg_type_of_underground_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_underground_created_at",
        on_entity="codes.type_of_underground",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_underground\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_type_of_underground_trg_type_of_underground_created_at)

    hame_plan_regulation_group_trg_plan_regulation_group_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_group_created_at",
        on_entity="hame.plan_regulation_group",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_plan_regulation_group_trg_plan_regulation_group_created_at)

    hame_document_trg_document_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_document_001_no_created_at_update",
        on_entity="hame.document",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_document_trg_document_001_no_created_at_update)

    codes_type_of_decision_maker_trg_type_of_decision_maker_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_decision_maker_001_no_created_at_update",
        on_entity="codes.type_of_decision_maker",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_decision_maker\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_decision_maker_trg_type_of_decision_maker_001_no_created_at_update
    )

    hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_001_no_created_at_update",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.lifecycle_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update)

    codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_legal_effects_of_master_plan_001_no_created_at_update",
        on_entity="codes.legal_effects_of_master_plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.legal_effects_of_master_plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_001_no_created_at_update
    )

    hame_organisation_trg_organisation_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_organisation_001_no_created_at_update",
        on_entity="hame.organisation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.organisation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_organisation_trg_organisation_001_no_created_at_update)

    codes_municipality_trg_municipality_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_municipality_001_no_created_at_update",
        on_entity="codes.municipality",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.municipality\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(codes_municipality_trg_municipality_001_no_created_at_update)

    codes_type_of_source_data_trg_type_of_source_data_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_source_data_001_no_created_at_update",
        on_entity="codes.type_of_source_data",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_source_data_trg_type_of_source_data_001_no_created_at_update
    )

    codes_language_trg_language_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_language_001_no_created_at_update",
        on_entity="codes.language",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.language\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(codes_language_trg_language_001_no_created_at_update)

    codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_name_of_plan_case_decision_001_no_created_at_update",
        on_entity="codes.name_of_plan_case_decision",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.name_of_plan_case_decision\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_001_no_created_at_update
    )

    codes_lifecycle_status_trg_lifecycle_status_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_lifecycle_status_001_no_created_at_update",
        on_entity="codes.lifecycle_status",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.lifecycle_status\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_lifecycle_status_trg_lifecycle_status_001_no_created_at_update
    )

    hame_event_date_trg_event_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_event_date_001_no_created_at_update",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.event_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_event_date_trg_event_date_001_no_created_at_update)

    codes_category_of_publicity_trg_category_of_publicity_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_category_of_publicity_001_no_created_at_update",
        on_entity="codes.category_of_publicity",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.category_of_publicity\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_category_of_publicity_trg_category_of_publicity_001_no_created_at_update
    )

    codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_verbal_plan_regulation_001_no_created_at_update",
        on_entity="codes.type_of_verbal_plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_verbal_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_001_no_created_at_update
    )

    codes_retention_time_trg_retention_time_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_retention_time_001_no_created_at_update",
        on_entity="codes.retention_time",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.retention_time\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(codes_retention_time_trg_retention_time_001_no_created_at_update)

    hame_plan_regulation_trg_plan_regulation_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_001_no_created_at_update",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_plan_regulation_trg_plan_regulation_001_no_created_at_update)

    hame_point_trg_point_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_point_001_no_created_at_update",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_point_trg_point_001_no_created_at_update)

    codes_type_of_additional_information_trg_type_of_additional_information_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_additional_information_001_no_created_at_update",
        on_entity="codes.type_of_additional_information",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_additional_information_trg_type_of_additional_information_001_no_created_at_update
    )

    codes_plan_type_trg_plan_type_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_plan_type_001_no_created_at_update",
        on_entity="codes.plan_type",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.plan_type\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(codes_plan_type_trg_plan_type_001_no_created_at_update)

    codes_type_of_processing_event_trg_type_of_processing_event_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_processing_event_001_no_created_at_update",
        on_entity="codes.type_of_processing_event",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_processing_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_processing_event_trg_type_of_processing_event_001_no_created_at_update
    )

    hame_land_use_area_trg_land_use_area_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_001_no_created_at_update",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_001_no_created_at_update)

    hame_plan_trg_plan_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_001_no_created_at_update",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_plan_trg_plan_001_no_created_at_update)

    hame_source_data_trg_source_data_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_source_data_001_no_created_at_update",
        on_entity="hame.source_data",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_source_data_trg_source_data_001_no_created_at_update)

    codes_plan_theme_trg_plan_theme_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_plan_theme_001_no_created_at_update",
        on_entity="codes.plan_theme",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.plan_theme\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(codes_plan_theme_trg_plan_theme_001_no_created_at_update)

    codes_type_of_document_trg_type_of_document_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_document_001_no_created_at_update",
        on_entity="codes.type_of_document",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_document_trg_type_of_document_001_no_created_at_update
    )

    hame_additional_information_trg_additional_information_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_additional_information_001_no_created_at_update",
        on_entity="hame.additional_information",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        hame_additional_information_trg_additional_information_001_no_created_at_update
    )

    codes_personal_data_content_trg_personal_data_content_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_personal_data_content_001_no_created_at_update",
        on_entity="codes.personal_data_content",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.personal_data_content\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_personal_data_content_trg_personal_data_content_001_no_created_at_update
    )

    hame_plan_proposition_trg_plan_proposition_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_001_no_created_at_update",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_proposition\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        hame_plan_proposition_trg_plan_proposition_001_no_created_at_update
    )

    hame_line_trg_line_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_line_001_no_created_at_update",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_line_trg_line_001_no_created_at_update)

    codes_type_of_interaction_event_trg_type_of_interaction_event_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_interaction_event_001_no_created_at_update",
        on_entity="codes.type_of_interaction_event",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_interaction_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_interaction_event_trg_type_of_interaction_event_001_no_created_at_update
    )

    codes_administrative_region_trg_administrative_region_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_administrative_region_001_no_created_at_update",
        on_entity="codes.administrative_region",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.administrative_region\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_administrative_region_trg_administrative_region_001_no_created_at_update
    )

    hame_other_area_trg_other_area_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_other_area_001_no_created_at_update",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_other_area_trg_other_area_001_no_created_at_update)

    codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_group_001_no_created_at_update",
        on_entity="codes.type_of_plan_regulation_group",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_001_no_created_at_update
    )

    codes_type_of_plan_regulation_trg_type_of_plan_regulation_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_001_no_created_at_update",
        on_entity="codes.type_of_plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_plan_regulation_trg_type_of_plan_regulation_001_no_created_at_update
    )

    codes_type_of_underground_trg_type_of_underground_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_underground_001_no_created_at_update",
        on_entity="codes.type_of_underground",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_underground\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        codes_type_of_underground_trg_type_of_underground_001_no_created_at_update
    )

    hame_plan_regulation_group_trg_plan_regulation_group_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_group_001_no_created_at_update",
        on_entity="hame.plan_regulation_group",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        hame_plan_regulation_group_trg_plan_regulation_group_001_no_created_at_update
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_regulation_group_trg_plan_regulation_group_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_group_001_no_created_at_update",
        on_entity="hame.plan_regulation_group",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        hame_plan_regulation_group_trg_plan_regulation_group_001_no_created_at_update
    )

    codes_type_of_underground_trg_type_of_underground_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_underground_001_no_created_at_update",
        on_entity="codes.type_of_underground",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_underground\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_underground_trg_type_of_underground_001_no_created_at_update
    )

    codes_type_of_plan_regulation_trg_type_of_plan_regulation_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_001_no_created_at_update",
        on_entity="codes.type_of_plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_plan_regulation_trg_type_of_plan_regulation_001_no_created_at_update
    )

    codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_group_001_no_created_at_update",
        on_entity="codes.type_of_plan_regulation_group",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_001_no_created_at_update
    )

    hame_other_area_trg_other_area_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_other_area_001_no_created_at_update",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_other_area_trg_other_area_001_no_created_at_update)

    codes_administrative_region_trg_administrative_region_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_administrative_region_001_no_created_at_update",
        on_entity="codes.administrative_region",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.administrative_region\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_administrative_region_trg_administrative_region_001_no_created_at_update
    )

    codes_type_of_interaction_event_trg_type_of_interaction_event_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_interaction_event_001_no_created_at_update",
        on_entity="codes.type_of_interaction_event",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_interaction_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_interaction_event_trg_type_of_interaction_event_001_no_created_at_update
    )

    hame_line_trg_line_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_line_001_no_created_at_update",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_line_trg_line_001_no_created_at_update)

    hame_plan_proposition_trg_plan_proposition_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_001_no_created_at_update",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_proposition\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_plan_proposition_trg_plan_proposition_001_no_created_at_update)

    codes_personal_data_content_trg_personal_data_content_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_personal_data_content_001_no_created_at_update",
        on_entity="codes.personal_data_content",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.personal_data_content\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_personal_data_content_trg_personal_data_content_001_no_created_at_update
    )

    hame_additional_information_trg_additional_information_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_additional_information_001_no_created_at_update",
        on_entity="hame.additional_information",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        hame_additional_information_trg_additional_information_001_no_created_at_update
    )

    codes_type_of_document_trg_type_of_document_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_document_001_no_created_at_update",
        on_entity="codes.type_of_document",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_type_of_document_trg_type_of_document_001_no_created_at_update)

    codes_plan_theme_trg_plan_theme_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_plan_theme_001_no_created_at_update",
        on_entity="codes.plan_theme",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.plan_theme\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_plan_theme_trg_plan_theme_001_no_created_at_update)

    hame_source_data_trg_source_data_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_source_data_001_no_created_at_update",
        on_entity="hame.source_data",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_source_data_trg_source_data_001_no_created_at_update)

    hame_plan_trg_plan_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_001_no_created_at_update",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_plan_trg_plan_001_no_created_at_update)

    hame_land_use_area_trg_land_use_area_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_001_no_created_at_update",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_001_no_created_at_update)

    codes_type_of_processing_event_trg_type_of_processing_event_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_processing_event_001_no_created_at_update",
        on_entity="codes.type_of_processing_event",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_processing_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_processing_event_trg_type_of_processing_event_001_no_created_at_update
    )

    codes_plan_type_trg_plan_type_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_plan_type_001_no_created_at_update",
        on_entity="codes.plan_type",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.plan_type\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_plan_type_trg_plan_type_001_no_created_at_update)

    codes_type_of_additional_information_trg_type_of_additional_information_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_additional_information_001_no_created_at_update",
        on_entity="codes.type_of_additional_information",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_additional_information_trg_type_of_additional_information_001_no_created_at_update
    )

    hame_point_trg_point_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_point_001_no_created_at_update",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_point_trg_point_001_no_created_at_update)

    hame_plan_regulation_trg_plan_regulation_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_001_no_created_at_update",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_plan_regulation_trg_plan_regulation_001_no_created_at_update)

    codes_retention_time_trg_retention_time_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_retention_time_001_no_created_at_update",
        on_entity="codes.retention_time",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.retention_time\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_retention_time_trg_retention_time_001_no_created_at_update)

    codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_verbal_plan_regulation_001_no_created_at_update",
        on_entity="codes.type_of_verbal_plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_verbal_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_001_no_created_at_update
    )

    codes_category_of_publicity_trg_category_of_publicity_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_category_of_publicity_001_no_created_at_update",
        on_entity="codes.category_of_publicity",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.category_of_publicity\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_category_of_publicity_trg_category_of_publicity_001_no_created_at_update
    )

    hame_event_date_trg_event_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_event_date_001_no_created_at_update",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.event_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_event_date_trg_event_date_001_no_created_at_update)

    codes_lifecycle_status_trg_lifecycle_status_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_lifecycle_status_001_no_created_at_update",
        on_entity="codes.lifecycle_status",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.lifecycle_status\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_lifecycle_status_trg_lifecycle_status_001_no_created_at_update)

    codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_name_of_plan_case_decision_001_no_created_at_update",
        on_entity="codes.name_of_plan_case_decision",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.name_of_plan_case_decision\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_001_no_created_at_update
    )

    codes_language_trg_language_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_language_001_no_created_at_update",
        on_entity="codes.language",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.language\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_language_trg_language_001_no_created_at_update)

    codes_type_of_source_data_trg_type_of_source_data_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_source_data_001_no_created_at_update",
        on_entity="codes.type_of_source_data",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_source_data_trg_type_of_source_data_001_no_created_at_update
    )

    codes_municipality_trg_municipality_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_municipality_001_no_created_at_update",
        on_entity="codes.municipality",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.municipality\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_municipality_trg_municipality_001_no_created_at_update)

    hame_organisation_trg_organisation_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_organisation_001_no_created_at_update",
        on_entity="hame.organisation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.organisation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_organisation_trg_organisation_001_no_created_at_update)

    codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_legal_effects_of_master_plan_001_no_created_at_update",
        on_entity="codes.legal_effects_of_master_plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.legal_effects_of_master_plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_001_no_created_at_update
    )

    hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_001_no_created_at_update",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.lifecycle_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update)

    codes_type_of_decision_maker_trg_type_of_decision_maker_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_type_of_decision_maker_001_no_created_at_update",
        on_entity="codes.type_of_decision_maker",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.type_of_decision_maker\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        codes_type_of_decision_maker_trg_type_of_decision_maker_001_no_created_at_update
    )

    hame_document_trg_document_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_document_001_no_created_at_update",
        on_entity="hame.document",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_document_trg_document_001_no_created_at_update)

    hame_plan_regulation_group_trg_plan_regulation_group_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_group_created_at",
        on_entity="hame.plan_regulation_group",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_plan_regulation_group_trg_plan_regulation_group_created_at)

    codes_type_of_underground_trg_type_of_underground_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_underground_created_at",
        on_entity="codes.type_of_underground",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_underground\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_type_of_underground_trg_type_of_underground_created_at)

    codes_type_of_plan_regulation_trg_type_of_plan_regulation_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_created_at",
        on_entity="codes.type_of_plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_type_of_plan_regulation_trg_type_of_plan_regulation_created_at)

    codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_plan_regulation_group_created_at",
        on_entity="codes.type_of_plan_regulation_group",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_type_of_plan_regulation_group_trg_type_of_plan_regulation_group_created_at
    )

    hame_other_area_trg_other_area_created_at = PGTrigger(
        schema="hame",
        signature="trg_other_area_created_at",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_other_area_trg_other_area_created_at)

    codes_administrative_region_trg_administrative_region_created_at = PGTrigger(
        schema="codes",
        signature="trg_administrative_region_created_at",
        on_entity="codes.administrative_region",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.administrative_region\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_administrative_region_trg_administrative_region_created_at)

    codes_type_of_interaction_event_trg_type_of_interaction_event_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_interaction_event_created_at",
        on_entity="codes.type_of_interaction_event",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_interaction_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_type_of_interaction_event_trg_type_of_interaction_event_created_at
    )

    hame_line_trg_line_created_at = PGTrigger(
        schema="hame",
        signature="trg_line_created_at",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_line_trg_line_created_at)

    hame_plan_proposition_trg_plan_proposition_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_created_at",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_proposition\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_plan_proposition_trg_plan_proposition_created_at)

    codes_personal_data_content_trg_personal_data_content_created_at = PGTrigger(
        schema="codes",
        signature="trg_personal_data_content_created_at",
        on_entity="codes.personal_data_content",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.personal_data_content\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_personal_data_content_trg_personal_data_content_created_at)

    hame_additional_information_trg_additional_information_created_at = PGTrigger(
        schema="hame",
        signature="trg_additional_information_created_at",
        on_entity="hame.additional_information",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_additional_information_trg_additional_information_created_at)

    codes_type_of_document_trg_type_of_document_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_document_created_at",
        on_entity="codes.type_of_document",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_type_of_document_trg_type_of_document_created_at)

    codes_plan_theme_trg_plan_theme_created_at = PGTrigger(
        schema="codes",
        signature="trg_plan_theme_created_at",
        on_entity="codes.plan_theme",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.plan_theme\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_plan_theme_trg_plan_theme_created_at)

    hame_source_data_trg_source_data_created_at = PGTrigger(
        schema="hame",
        signature="trg_source_data_created_at",
        on_entity="hame.source_data",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_source_data_trg_source_data_created_at)

    hame_plan_trg_plan_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_created_at",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_plan_trg_plan_created_at)

    hame_land_use_area_trg_land_use_area_created_at = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_created_at",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_created_at)

    codes_type_of_processing_event_trg_type_of_processing_event_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_processing_event_created_at",
        on_entity="codes.type_of_processing_event",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_processing_event\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_type_of_processing_event_trg_type_of_processing_event_created_at
    )

    codes_plan_type_trg_plan_type_created_at = PGTrigger(
        schema="codes",
        signature="trg_plan_type_created_at",
        on_entity="codes.plan_type",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.plan_type\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_plan_type_trg_plan_type_created_at)

    codes_type_of_additional_information_trg_type_of_additional_information_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_additional_information_created_at",
        on_entity="codes.type_of_additional_information",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_type_of_additional_information_trg_type_of_additional_information_created_at
    )

    hame_point_trg_point_created_at = PGTrigger(
        schema="hame",
        signature="trg_point_created_at",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_point_trg_point_created_at)

    hame_plan_regulation_trg_plan_regulation_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_created_at",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_plan_regulation_trg_plan_regulation_created_at)

    codes_retention_time_trg_retention_time_created_at = PGTrigger(
        schema="codes",
        signature="trg_retention_time_created_at",
        on_entity="codes.retention_time",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.retention_time\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_retention_time_trg_retention_time_created_at)

    codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_verbal_plan_regulation_created_at",
        on_entity="codes.type_of_verbal_plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_verbal_plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_type_of_verbal_plan_regulation_trg_type_of_verbal_plan_regulation_created_at
    )

    codes_category_of_publicity_trg_category_of_publicity_created_at = PGTrigger(
        schema="codes",
        signature="trg_category_of_publicity_created_at",
        on_entity="codes.category_of_publicity",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.category_of_publicity\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_category_of_publicity_trg_category_of_publicity_created_at)

    hame_event_date_trg_event_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_created_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.event_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_event_date_trg_event_date_created_at)

    codes_lifecycle_status_trg_lifecycle_status_created_at = PGTrigger(
        schema="codes",
        signature="trg_lifecycle_status_created_at",
        on_entity="codes.lifecycle_status",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.lifecycle_status\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_lifecycle_status_trg_lifecycle_status_created_at)

    codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_created_at = PGTrigger(
        schema="codes",
        signature="trg_name_of_plan_case_decision_created_at",
        on_entity="codes.name_of_plan_case_decision",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.name_of_plan_case_decision\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_name_of_plan_case_decision_trg_name_of_plan_case_decision_created_at
    )

    codes_language_trg_language_created_at = PGTrigger(
        schema="codes",
        signature="trg_language_created_at",
        on_entity="codes.language",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.language\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_language_trg_language_created_at)

    codes_type_of_source_data_trg_type_of_source_data_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_source_data_created_at",
        on_entity="codes.type_of_source_data",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_type_of_source_data_trg_type_of_source_data_created_at)

    codes_municipality_trg_municipality_created_at = PGTrigger(
        schema="codes",
        signature="trg_municipality_created_at",
        on_entity="codes.municipality",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.municipality\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_municipality_trg_municipality_created_at)

    hame_organisation_trg_organisation_created_at = PGTrigger(
        schema="hame",
        signature="trg_organisation_created_at",
        on_entity="hame.organisation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.organisation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_organisation_trg_organisation_created_at)

    codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_created_at = PGTrigger(
        schema="codes",
        signature="trg_legal_effects_of_master_plan_created_at",
        on_entity="codes.legal_effects_of_master_plan",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.legal_effects_of_master_plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        codes_legal_effects_of_master_plan_trg_legal_effects_of_master_plan_created_at
    )

    hame_lifecycle_date_trg_lifecycle_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_created_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.lifecycle_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_created_at)

    codes_type_of_decision_maker_trg_type_of_decision_maker_created_at = PGTrigger(
        schema="codes",
        signature="trg_type_of_decision_maker_created_at",
        on_entity="codes.type_of_decision_maker",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.type_of_decision_maker\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_type_of_decision_maker_trg_type_of_decision_maker_created_at)

    hame_document_trg_document_created_at = PGTrigger(
        schema="hame",
        signature="trg_document_created_at",
        on_entity="hame.document",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_document_trg_document_created_at)

    hame_trgfunc_no_created_at_update = PGFunction(
        schema="hame",
        signature="trgfunc_no_created_at_update()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.created_at = OLD.created_at;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_no_created_at_update)

    hame_trgfunc_created_at = PGFunction(
        schema="hame",
        signature="trgfunc_created_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.created_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_created_at)

    # ### end Alembic commands ###
