"""add document etag field

Revision ID: 3ff7fafa3cca
Revises: f5dad001cfff
Create Date: 2025-04-04 13:07:56.016022

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ff7fafa3cca"
down_revision: Union[str, None] = "f5dad001cfff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("exported_file_etag", sa.String(), nullable=True),
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "exported_file_etag", schema="hame")
    # ### end Alembic commands ###
